In [1]:
print('Hello')


Hello


In [4]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3,4))
np.random.random(size=(3,4))

array([[0.58629185, 0.80871661, 0.65418124, 0.64734333],
       [0.42397315, 0.44691555, 0.82792951, 0.4556437 ],
       [0.19724321, 0.17143756, 0.8952057 , 0.21361423]])

In [5]:
from numpy.random import normal

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype



dtype('float64')

In [6]:
#ndarray,陣列運算
normal_value * 10

array([[ -7.9987627 ,  26.00953654,  23.74457081, -11.32165364],
       [-15.32134662,   1.44781383,  -6.45888023,   1.56937762],
       [  3.25008128,   1.99300361, -11.46328623,   6.16406277]])

In [7]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([ 3.0433691 , -1.87630354, -0.00561386])